_wandb:
    value:
        cli_version: 0.25.0
        e:
            7sxh66oykkpd0vi32jkv5miw8q8cuqqa:
                args:
                    - --optimizer
                    - rmsprop
                    - --loss
                    - mse
                cpu_count: 8
                cpu_count_logical: 12
                disk:
                    /:
                        total: "509722226688"
                        used: "215375872000"
                email: ee24d044@smail.iitm.ac.in
                executable: C:\Users\annad\DL\da6401_assignment_1\venv\Scripts\python.exe
                git:
                    commit: dc84977f2f993e478bb932f0c5a4725707d72fb5
                    remote: https://github.com/sreedeepthiatsd/da6401_assignment_1
                host: Sreedeepthi
                memory:
                    total: "16857817088"
                os: Windows-11-10.0.26200-SP0
                program: -m src.train
                python: CPython 3.12.4
                root: C:\Users\annad\DL\da6401_assignment_1
                startedAt: "2026-03-06T08:27:18.195342Z"
                writerId: 7sxh66oykkpd0vi32jkv5miw8q8cuqqa
        m: []
        python_version: 3.12.4
        t:
            "1":
                - 2
                - 3
                - 5
                - 53
            "2":
                - 2
                - 3
                - 5
                - 53
            "3":
                - 2
                - 16
            "4": 3.12.4
            "5": 0.25.0
            "8":
                - 3
            "12": 0.25.0
            "13": windows-amd64
activation:
    value: relu
batch_size:
    value: 32
dataset:
    value: mnist
epochs:
    value: 10
hidden_size:
    value:
        - 128
        - 128
        - 128
learning_rate:
    value: 0.001
loss:
    value: mse
model_save_path:
    value: models/best_model.npy
num_layers:
    value: 3
optimizer:
    value: rmsprop
wandb_entity:
    value: ee24d044-indian-institute-of-technology-madras
wandb_project:
    value: dl_assignment_1
weight_init:
    value: xavier
